name: draggable_range_selector
description: Flutter widget for selecting ranges of items with draggable handles.
version: 1.0.1
homepage: https://github.com/AIPEAC/draggable-range-selector
repository: https://github.com/AIPEAC/draggable-range-selector
issue_tracker: https://github.com/AIPEAC/draggable-range-selector/issues
documentation: https://github.com/AIPEAC/draggable-range-selector#readme

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
